apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.27
    #image: busybox:musl
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    imagePullPolicy: IfNotPresent

