apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"crfchina.com": ["192.168.66.11"]}
  upstreamNameservers: |
    ["192.168.66.11", "8.8.8.8", "4.4.4.4"]
